version: '3'
services:
  frontend:
    build:
      context: ./Frontend
    ports:
      - "8080:8080"
    volumes:
      - ./Frontend:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app
