services:
  backend:
    build: ./Backend
    ports:
      - "5001:5001"  # Exponuje backend port
    command: ["python", "audio_processor.py"]
    volumes:
      - ./Backend:/app  # Přidání volume pro backend, aby se změny ihned projevily

  frontend:
    build: ./Frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5001  # URL pro přístup k backendu
    volumes:
      - ./Frontend:/app  # Přidání volume pro frontend
      - ./Backend:/app/Backend  # Zde přidáváme backend pro frontend

