services:
  backend:
    build: ./Backend
    ports:
      - "5001:5001"  # Expose backend on port 5001
    command: ["python", "audio_processor.py"]
    volumes:
      - ./Backend:/app  # Volume for backend to reflect code changes

  frontend:
    build: ./Frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5001  # Backend URL for API access
    volumes:
      - ./Frontend:/app  # Volume for frontend to reflect code changes
